export const actionHome = {
  GET_WELCOME_TEXT: 'GET_WELCOME_TEXT',
  GET_NEWS: 'GET_NEWS',
  SET_SLIDE: 'SET_SLIDE',
  SET_WELCOME_TEXT: 'SET_WELCOME_TEXT'
};

export const actionUser = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  GET_LOGGED: 'GET_LOGGED_USER_INFO'
};
